/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topicos2015a;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Oscar
 */
public class Topicos2015A extends javax.swing.JFrame {
    JTable tblDatos = new JTable();
    Clibro Datos[]=new Clibro[5];
    int cont;
    DefaultTableModel MT;
    String Registro[][]={};
    String cabecera[]={"ISBN","Titulo"};

    
    /**
     * Creates new form frmLibro
     */
    public Topicos2015A() {
        initComponents();
        MT=new DefaultTableModel(Registro, cabecera);
       tbl.setModel(MT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtMSG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Biblioteca virtual");
        Jpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 200, 30));

        jLabel2.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel2.setText("Titulo");
        Jpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, 40));

        jLabel3.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel3.setText("ISBN");
        Jpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, 40));

        txtISBN.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Jpanel.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 270, 30));

        txtTitulo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        Jpanel.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 270, 30));

        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        Jpanel.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 90, 40));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbl);

        Jpanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 490, 150));
        Jpanel.add(txtMSG, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 320, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try
        {
        Datos[cont] = new Clibro();
        Datos[cont].setISBN(txtISBN.getText());
        Datos[cont].setTitulo(txtTitulo.getText());
        String fila[]={Datos[cont].getISBN(),Datos[cont].getTitulo()};
        MT.addRow(fila);
        cont++;
        }
        catch(ArrayIndexOutOfBoundsException arreglo)
        {
           txtMSG.setText("Sobrepasa el tamaño del arreglo");
        }
        catch(ExceptionLibro errorISBN)
        {
            txtMSG.setText(errorISBN.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Topicos2015A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Topicos2015A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Topicos2015A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Topicos2015A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Topicos2015A().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JLabel txtMSG;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
